import json
import os

goals = []

def g(name, tier, types, req=None, any_of=None):
    goals.append({
        "name": name,
        "difficulty": tier,
        "types": types,
        "requiredItems": req or [],
        "requiredAnyOf": any_of or []
    })

entries = [
    (1, "Open Clock Town Chest", ["clocktown"], []),
    (1, "Get Deku Mask", ["mask", "deku"], []),
    (1, "Get Bomber's Notebook", ["clocktown"], []),
    (1, "Get Song of Healing", ["song"], []),
    (1, "Get Hero's Shield", ["item"], []),
    (2, "Get Kokiri Sword", ["item"], []),
    (2, "Get Deku Stick", ["item"], []),
    (2, "Get Deku Nuts", ["item"], []),
    (2, "Get Clocktown Map", ["map"], []),
    (2, "Unlock Odolwa's Door", ["wft", "action"], []),
    (3, "Get Sonata of Awakening", ["song", "wft"], []),
    (3, "Get Woodfall Map", ["map", "wft"], []),
    (3, "Get Woodfall Compass", ["wft"], []),
    (3, "Get Woodfall Boss Key", ["wft"], []),
    (3, "Get 3 Bottom Row Songs", ["song"], []),
    (4, "Get Bow", ["item", "wft"], ["Bow"]),
    (4, "Get Deku Princess", ["bottle", "wft"], ["Deku Princess"]),
    (4, "Get Room Key", ["item", "clocktown"], ["Room Key"]),
    (4, "Get Postman's Hat", ["mask"], ["Postman's Hat"]),
    (4, "Get Keaton Mask", ["mask"], ["Keaton Mask"]),
    (5, "Get Goron Mask", ["mask", "goron"], ["Goron Mask"]),
    (5, "Get Powder Keg", ["item", "goron"], ["Powder Keg"]),
    (5, "Get Goron Lullaby", ["song", "goron"], ["Goron Lullaby"]),
    (5, "Lullaby Intro", ["song", "goron"], []),
    (5, "Get Snowhead Map", ["map", "sht"], []),
    (6, "Get Zora Mask", ["mask", "zora"], ["Zora Mask"]),
    (6, "Get Hookshot", ["item", "gbt"], ["Hookshot"]),
    (6, "Get New Wave Bossa Nova", ["song", "zora"], ["New Wave Bossa Nova"]),
    (6, "Get Great Bay Map", ["map", "gbt"], []),
    (6, "Get Pictograph Box", ["item"], ["Pictograph Box"]),
    (7, "Get Gibdo Mask", ["mask", "ikana"], ["Gibdo Mask"]),
    (7, "Get Garo Mask", ["mask", "ikana"], ["Garo Mask"]),
    (7, "Get Captain's Hat", ["mask", "ikana"], ["Captain's Hat"]),
    (7, "Get Mirror Shield", ["item"], ["Mirror Shield"]),
    (7, "Get Lens of Truth", ["item"], ["Lens of Truth"]),
    (8, "Get Mask of Truth", ["mask"], ["Mask of Truth"]),
    (8, "Get Mask of Scents", ["mask"], ["Mask of Scents"]),
    (8, "Get Kamaro's Mask", ["mask"], ["Kamaro's Mask"]),
    (8, "Get Stone Mask", ["mask"], ["Stone Mask"]),
    (8, "Get All-Night Mask", ["mask"], ["All-Night Mask"]),
    (9, "Get Romani's Mask", ["mask"], ["Romani's Mask"]),
    (9, "Get Kafei's Mask", ["mask"], ["Kafei's Mask"]),
    (9, "Get Couple's Mask", ["mask"], ["Couple's Mask"]),
    (9, "Get Bunny Hood", ["mask"], ["Bunny Hood"]),
    (9, "Get Bremen Mask", ["mask"], ["Bremen Mask"]),
    (10, "Get Don Gero's Mask", ["mask"], ["Don Gero's Mask"]),
    (10, "Get Circus Leader's Mask", ["mask"], ["Circus Leader's Mask"]),
    (10, "Get 5 East Clock Town HPs", ["hp", "clocktown"], []),
    (10, "Get 5 Termina Grotto HPs", ["hp", "field"], []),
    (10, "Get Postman's Hat HP", ["hp", "clocktown"], ["Postman's Hat"]),
    (11, "Get Fire Arrow", ["item", "arrow"], ["Fire Arrow"]),
    (11, "Get Ice Arrow", ["item", "arrow"], ["Ice Arrow"]),
    (11, "Get Light Arrow", ["item", "arrow"], ["Light Arrow"]),
    (11, "Get 7 songs", ["song"], []),
    (11, "Get Elegy of Emptiness", ["song", "ikana"], ["Elegy of Emptiness"]),
    (12, "Get Oath to Order", ["song"], ["Oath to Order"]),
    (12, "Get Song of Storms", ["song"], ["Song of Storms"]),
    (12, "Get Epona's Song", ["song"], ["Epona's Song"]),
    (12, "Get Song of Soaring", ["song"], ["Song of Soaring"]),
    (12, "Get 3 Temple Maps and Compasses", ["dungeon"], []),
    (13, "Get Fierce Deity Mask", ["mask", "moon"], ["Fierce Deity Mask"]),
    (13, "Get Giant's Mask", ["mask", "stt"], ["Giant's Mask"]),
    (13, "Get Great Fairy's Sword", ["item"], ["Great Fairy's Sword"]),
    (13, "Get Gilded Sword", ["item"], ["Gilded Sword"]),
    (13, "Get Razor Sword", ["item"], ["Razor Sword"]),
    (14, "Kill 3 Dinolfos", ["combat"], []),
    (14, "Open 2 Graves", ["ikana", "action"], ["Captain's Hat"]),
    (14, "Ghost Hut HP", ["hp", "ikana"], []),
    (14, "Get 2 Great Fairy Rewards", ["fairy"], []),
    (15, "Unbar 5 doors in the Well", ["ikana", "well"], ["Gibdo Mask"]),
    (15, "Save Sun Mask", ["ikana", "kafei"], ["Kafei's Mask"]),
    (15, "Get All 4 Business Scrub HPs", ["hp", "scrub"], []),
    (15, "Get 20 Total Stray Fairies", ["fairy"], []),
    (16, "Open 11 Pirates' Fortress area Chests", ["pirates", "gbt"], ["Hookshot"]),
    (16, "Destroy 15 SHT Ice Blocks", ["sht", "action"], ["Goron Mask"]),
    (16, "Remove All Blocks from SHT Pillar", ["sht", "action"], ["Goron Mask"]),
    (16, "Get 2 Temple Maps, Compasses, and Boss Keys", ["dungeon"], []),
    (17, "Cremia's Reward (hug or 200 rupees)", ["ranch"], ["Romani's Mask"]),
    (17, "Get All Notebook Pictures", ["notebook"], ["Bomber's Notebook"]),
    (17, "Get 3 Happiness Seals", ["notebook"], ["Bomber's Notebook"]),
    (17, "Get 5 Happiness Seals", ["notebook"], ["Bomber's Notebook"]),
    (17, "Pictograph of Dancing Redead", ["pictograph"], ["Pictograph Box"]),
    (18, "Get 10 Unique Bottle Contents", ["bottle"], []),
    (18, "Get Chateau Romani", ["bottle", "ranch"], ["Chateau Romani"]),
    (18, "Get Big Poe", ["bottle"], ["Big Poe"]),
    (18, "Get Gold Dust", ["bottle", "smithy"], ["Gold Dust"]),
    (18, "Rock Sirloin Above Head", ["goron", "item"], ["Goron Mask"]),
    (19, "Clear All Chest Icons on Woodfall Map", ["map", "wft"], ["Woodfall Map"]),
    (19, "Clear All Chest Icons on Snowhead Map", ["map", "sht"], ["Snowhead Map"]),
    (19, "Clear All Chest Icons on Great Bay Map", ["map", "gbt"], ["Great Bay Map"]),
    (19, "Clear All Chest Icons on Stone Tower Map", ["map", "stt"], ["Stone Tower Map"]),
    (19, "Open chest of Magic Beans", ["stt"], ["Magic Beans"]),
    (20, "Get Giant Wallet", ["wallet"], ["Giant Wallet"]),
    (20, "Get Adult Wallet", ["wallet"], ["Adult Wallet"]),
    (20, "Get Big Bomb Bag", ["item"], ["Big Bomb Bag"]),
    (20, "Get Largest Quiver", ["item"], ["Largest Quiver"]),
    (20, "Diagonal of 4 Item Slots", ["inventory"], []),
    (21, "No Hidden Owl Statue", ["clocktown", "action"], []),
    (21, "Get Moon's Tear", ["item", "clocktown"], ["Moon's Tear"]),
    (21, "Get Pendant of Memories", ["item", "kafei"], ["Pendant of Memories"]),
    (21, "Get Letter to Kafei", ["item"], ["Letter to Kafei"]),
    (21, "Get Express Letter to Mama", ["item"], ["Express Letter to Mama"]),
    (22, "Get Odolwa's Remains", ["remain", "wft"], ["Odolwa's Remains"]),
    (22, "Get Goht's Remains", ["remain", "sht"], ["Goht's Remains"]),
    (22, "Get Gyorg's Remains", ["remain", "gbt"], ["Gyorg's Remains"]),
    (22, "Get Twinmold's Remains", ["remain", "stt"], ["Twinmold's Remains"]),
    (22, "Get 4 Remains", ["remain"], []),
    (23, "Beat Woodfall Temple", ["wft", "boss"], ["Deku Mask"]),
    (23, "Beat Snowhead Temple", ["sht", "boss"], ["Goron Mask"]),
    (23, "Beat Great Bay Temple", ["gbt", "boss"], ["Zora Mask"]),
    (23, "Beat Stone Tower Temple", ["stt", "boss"], ["Gibdo Mask"]),
    (23, "Beat 2 Temples", ["dungeon"], []),
    (24, "Reach Moon", ["moon"], ["Oath to Order"]),
    (24, "Get All Masks", ["mask"], []),
    (24, "Get All Songs", ["song"], []),
    (24, "Get All Heart Containers", ["hp"], []),
    (25, "100% Bombers Notebook", ["notebook"], ["Bomber's Notebook"]),
    (25, "Blackout All Dungeons", ["dungeon"], []),
    (25, "Get All Stray Fairies", ["fairy"], []),
    (25, "Complete Title Deed Quest", ["scrub", "quest"], ["Land Title Deed"]),
    (25, "Full Inventory", ["inventory"], []),
]

for tier, name, types, req in entries:
    g(name, tier, types, req)

g("Defeat Garo Ninja", 14, ["combat", "ikana"], [], [["Garo Mask"], ["Light Arrow"]])
g("Change GBT Water Direction", 16, ["gbt", "action"], ["Hookshot", "Zora Mask"])
g("Gold Rupee from Ikana Business Scrub", 15, ["scrub", "ikana"],
  ["Mountain Title Deed", "Swamp Title Deed", "Land Title Deed", "Ocean Title Deed"])
g("Beat Majora", 24, ["moon", "boss"], ["Fierce Deity Mask"])

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out_path = os.path.join(root, "MMR_GUI", "Data", "mm_bingo_standard.json")
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w", encoding="utf-8") as f:
    json.dump({"version": "standard-v5", "goals": goals}, f, indent=2, ensure_ascii=False)
print("Wrote", len(goals), "goals")
